# -*- coding: utf-8 -*-
#
TXT_DIR    = "#{Dir.pwd}/meals/"
OUTPUT_DIR = "#{Dir.pwd}/reports/"

FILE_EXT = '.txt'
MEALS = [
  {name: 'breakfast' , label: '아침'} ,
  {name: 'lunch' , label: '점심'} ,
  {name: 'dinner' , label: '저녁'}
]

task :default => :daily_report

desc '하루의 식사 일지를 기록한다'
task :daily_report => [:check, :report] do
  puts '하루의 식사 일지를 기록했습니다'
end

desc '식사 일지 파일 확인'
task :check do
  MEALS.each do |meal|
    file_name = meal[:name] + FILE_EXT
    full_path = TXT_DIR + file_name

    if File.exist?(full_path)
      puts "#{file_name} OK"
    else
      puts "#{file_name}이 없습니다"
    end
  end
end

desc '식사 보고서 작성'
task :report do
  date_str = Time.now.strftime('%Y/%m/%d')
  output_str = "#{date_str}의 식사 일지\n \n"
  MEALS.each do |meal|
    file_name = meal[:name] + FILE_EXT
    full_path = TXT_DIR + file_name

    description = <<DESC
#{meal[:label]}
#{File.read(full_path, :encoding => Encoding::UTF_8)}
DESC

    output_str += description
  end

  output_file = OUTPUT_DIR + "report_#{Time.now.strftime('%Y%m%d')}.txt"
  File.open(output_file, 'w') { |f|
    f.write output_str
  }
end
